version: 0.2

phases:
  install:
    runtime-versions:
      linux: 1
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Nothing to do in the pre_build phase...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'index.html'
    - 'script.js'
    - 'styles.css'
    - 'appspec.yml'
    - 'scripts/before_install.sh'
    - 'scripts/after_install.sh'    
    - 'scripts/start_server.sh'
    - 'scripts/stop_server.sh'